### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by randomjoh** [cvmiller/show_wifi_password#1]
./show_wifi_passwd.sh: 8: ./show_wifi_passwd.sh: Syntax error: newline unexpected

Running in xfce4 crouton on Chrome OS

**Comment by cvmiller** [comment]
Interesting, line 8 is a comment line, so not sure what is going wrong there.
Can you run the program with debug turned on and past the debug info into this issue? run as:
sh -x ./show_wifi_passwd.sh -f <shill.profile file>

Please don't copy the Wifi passwords into this issue.

thx.

**Comment by cvmiller** [comment]
Closing.
